export const ALL_PERMISSIONS = [
  { code: "dashboard.view", module: "dashboard", description: "View role dashboard" },
  { code: "patient.view", module: "patient", description: "View patient records" },
  { code: "patient.create", module: "patient", description: "Register patients" },
  { code: "patient.edit", module: "patient", description: "Edit patient demographics" },
  { code: "appointment.view", module: "appointment", description: "View appointments" },
  { code: "appointment.create", module: "appointment", description: "Book appointments" },
  { code: "appointment.reschedule", module: "appointment", description: "Reschedule appointments" },
  { code: "appointment.cancel", module: "appointment", description: "Cancel appointments" },
  { code: "appointment.checkin", module: "appointment", description: "Check in patients" },
  { code: "queue.manage", module: "appointment", description: "Manage doctor queues" },
  { code: "consultation.view", module: "consultation", description: "View encounters" },
  { code: "consultation.create", module: "consultation", description: "Start and edit draft encounters" },
  { code: "consultation.finalize", module: "consultation", description: "Finalize encounters" },
  { code: "vitals.record", module: "consultation", description: "Record vitals" },
  { code: "prescription.view", module: "prescription", description: "View prescriptions" },
  { code: "prescription.create", module: "prescription", description: "Create prescriptions" },
  { code: "prescription.print", module: "prescription", description: "Print prescriptions" },
  { code: "pharmacy.medicine.view", module: "pharmacy", description: "View medicine catalogue" },
  { code: "pharmacy.medicine.manage", module: "pharmacy", description: "Manage medicine catalogue" },
  { code: "pharmacy.batch.view", module: "pharmacy", description: "View batches" },
  { code: "pharmacy.batch.create", module: "pharmacy", description: "Create batches via purchase" },
  { code: "pharmacy.purchase.view", module: "pharmacy", description: "View purchases" },
  { code: "pharmacy.purchase.create", module: "pharmacy", description: "Receive purchases" },
  { code: "pharmacy.sale.create", module: "pharmacy", description: "Dispense / sell medicines" },
  { code: "pharmacy.sale.refund", module: "pharmacy", description: "Pharmacy sale returns" },
  { code: "inventory.view", module: "inventory", description: "View stock" },
  { code: "inventory.adjust", module: "inventory", description: "Adjust stock" },
  { code: "supplier.manage", module: "inventory", description: "Manage suppliers" },
  { code: "billing.view", module: "billing", description: "View invoices" },
  { code: "billing.create", module: "billing", description: "Create invoices" },
  { code: "billing.pay", module: "billing", description: "Record payments" },
  { code: "billing.refund", module: "billing", description: "Issue refunds" },
  { code: "billing.cancel", module: "billing", description: "Cancel invoices" },
  { code: "lab.catalogue.manage", module: "lab", description: "Manage lab catalogue" },
  { code: "lab.order.view", module: "lab", description: "View lab orders" },
  { code: "lab.order.create", module: "lab", description: "Create lab orders" },
  { code: "lab.sample.collect", module: "lab", description: "Collect samples" },
  { code: "lab.result.enter", module: "lab", description: "Enter lab results" },
  { code: "lab.result.verify", module: "lab", description: "Verify lab results" },
  { code: "lab.report.print", module: "lab", description: "Print lab reports" },
  { code: "user.view", module: "admin", description: "View users" },
  { code: "user.create", module: "admin", description: "Create users" },
  { code: "user.edit", module: "admin", description: "Edit users and roles" },
  { code: "user.disable", module: "admin", description: "Disable or reactivate users" },
  { code: "user.reset_password", module: "admin", description: "Reset user credentials" },
  { code: "role.manage", module: "admin", description: "Modify role permissions" },
  { code: "department.manage", module: "admin", description: "Manage departments and designations" },
  { code: "doctor.manage", module: "admin", description: "Manage doctor profiles and schedules" },
  { code: "settings.manage", module: "admin", description: "Change system settings" },
  { code: "audit.view", module: "security", description: "View audit logs" },
  { code: "backup.manage", module: "system", description: "Run and restore backups" },
  { code: "health.view", module: "system", description: "View system health" },
  { code: "reports.clinical", module: "reports", description: "Clinical reports" },
  { code: "reports.pharmacy", module: "reports", description: "Pharmacy reports" },
  { code: "reports.financial", module: "reports", description: "Financial reports" },
  { code: "reports.lab", module: "reports", description: "Laboratory reports" },
  { code: "reports.audit", module: "reports", description: "Audit reports" },
] as const;

export type PermissionCode = (typeof ALL_PERMISSIONS)[number]["code"];

export const ROLE_CODES = [
  "super_admin",
  "admin",
  "doctor",
  "nurse",
  "receptionist",
  "pharmacist",
  "store_manager",
  "lab_technician",
  "lab_attendant",
  "lab_verifier",
  "accountant",
  "security_officer",
] as const;

export type RoleCode = (typeof ROLE_CODES)[number];

const allCodes = ALL_PERMISSIONS.map((p) => p.code);

export const ROLE_PERMISSIONS: Record<RoleCode, readonly string[]> = {
  super_admin: allCodes,
  admin: allCodes.filter((c) => c !== "backup.manage"),
  doctor: [
    "dashboard.view",
    "patient.view",
    "appointment.view",
    "queue.manage",
    "consultation.view",
    "consultation.create",
    "consultation.finalize",
    "vitals.record",
    "prescription.view",
    "prescription.create",
    "prescription.print",
    "lab.order.view",
    "lab.order.create",
    "lab.report.print",
    "billing.view",
    "reports.clinical",
  ],
  nurse: [
    "dashboard.view",
    "patient.view",
    "patient.edit",
    "appointment.view",
    "appointment.checkin",
    "queue.manage",
    "consultation.view",
    "vitals.record",
    "lab.order.view",
    "lab.sample.collect",
  ],
  receptionist: [
    "dashboard.view",
    "patient.view",
    "patient.create",
    "patient.edit",
    "appointment.view",
    "appointment.create",
    "appointment.reschedule",
    "appointment.cancel",
    "appointment.checkin",
    "billing.view",
    "billing.create",
    "billing.pay",
  ],
  pharmacist: [
    "dashboard.view",
    "patient.view",
    "prescription.view",
    "pharmacy.medicine.view",
    "pharmacy.batch.view",
    "pharmacy.purchase.view",
    "pharmacy.sale.create",
    "pharmacy.sale.refund",
    "inventory.view",
    "billing.view",
    "billing.create",
    "billing.pay",
    "reports.pharmacy",
  ],
  store_manager: [
    "dashboard.view",
    "pharmacy.medicine.view",
    "pharmacy.medicine.manage",
    "pharmacy.batch.view",
    "pharmacy.batch.create",
    "pharmacy.purchase.view",
    "pharmacy.purchase.create",
    "inventory.view",
    "inventory.adjust",
    "supplier.manage",
    "reports.pharmacy",
  ],
  lab_technician: [
    "dashboard.view",
    "patient.view",
    "lab.order.view",
    "lab.result.enter",
    "lab.report.print",
    "reports.lab",
  ],
  lab_attendant: [
    "dashboard.view",
    "patient.view",
    "lab.order.view",
    "lab.sample.collect",
  ],
  lab_verifier: [
    "dashboard.view",
    "patient.view",
    "lab.order.view",
    "lab.result.enter",
    "lab.result.verify",
    "lab.report.print",
    "reports.lab",
  ],
  accountant: [
    "dashboard.view",
    "patient.view",
    "billing.view",
    "billing.create",
    "billing.pay",
    "billing.refund",
    "billing.cancel",
    "reports.financial",
  ],
  security_officer: [
    "dashboard.view",
    "user.view",
    "audit.view",
    "health.view",
    "reports.audit",
  ],
};
